from os.path import join as pjoin

# configfile: "config/config.yaml"

FA = config["fa"]
VCF = config["vcf"]
WD = config["wd"]
TRF = config["trf"]
REALFQ = config["fq"]

sample = "HG02723"
seed = 23
coverage = 5

Ls = [32, 128, 512]  # vertices max size
Ks = [27]  # anchor size


include: "rules/simulation.smk"
include: "rules/callers.smk"
include: "rules/pansv.smk"
include: "rules/gal.smk"


rule run:
    input:
        pjoin(WD, sample, "cutesv", "variations-w2.vcf"),
        pjoin(WD, sample, "sniffles", "variations.vcf"),
        expand(
            pjoin(WD, sample, "pansv-l{l}", "{graph}-calls.k{k}.txt"),
            l=Ls,
            k=Ks,
            graph=["reference", "variations"],
        ),
        expand(
            pjoin(WD, sample, "graphaligner-l{l}", "{graph}.gaf"),
            l=Ls,
            graph=["reference", "variations"],
        ),
