seed: 23
fa: /data/hprc-chm13.v2/region.fa
bed: /data/hprc-chm13.v2/x.bed
gbz: /data/hprc-chm13.v2/region.gbz
samples: /data/hprc-chm13.v2/all_samples.list
realfq: /data/reads-4sampling/PB.SequelII.fq
wd: /data/hprc-chm13.v2/region-23-OUT
ref: CHM13
coverage: 15
ns:
  - 0
  # - 1
  # - 8
  # - 32
  # - 64
ds:
  # - 0.1
  - 0.33
  - 0.5
  - 0.75
  #- 1.0
cs:
  - 0.75
  - 0.9
  - 0.95
ms:
  - 7
  - 11
  - 15
tools:
  cactus: /home/ld/software/cactus/cactus_env/bin/activate
  hifiasm-custom: /home/ld/code/hifiasm/hifiasm