seed: 42
fa: /scratch/luca-palss/chr16.fa
bed: /scratch/luca-palss/chr16.segdups.bed
gbz: /scratch/luca-palss/chr16.gbz
samples: /scratch/luca-palss/hprc-v2.0.samples.list
realfq: /scratch/luca-palss/seqII2.0.real.fq
wd: /scratch2/luca-palss/chr16-out.15x.42-2
ref: CHM13
coverage: 15
ns:
  - 1
  - 8
  - 32
  # - 64
ds:
  - 0.1
  #- 0.5
  #- 1.0
cs:
  - 0.9
  - 0.95
ms:
  - 7
  - 11
